name: Daily Update Submodule

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-submodule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Update submodule to latest commit
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive

          git submodule update --remote --recursive --checkout backend_node frontend_react web_deployment

          git add backend_node frontend_react web_deployment
          git -c user.name="github-actions[bot]" -c user.email="41898282+github-actions[bot]@users.noreply.github.com" \
            commit -m "chore: daily update submodule" || echo "No changes to commit"
          git push
