name: Daily Update Submodule

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-submodule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Update submodule to latest commit
        run: |
          git submodule update --remote --merge
          git add path/to/your-submodule
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "chore: daily update submodule" || echo "No changes to commit"
          git push
